INSERT INTO movie_genre ( name, url ) VALUES ( 'Travel & Adventure Documentaries', 'travel-adventure-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'General Strength & Flexibility', 'general-strength-flexibility' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Anime Dramas', 'anime-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Independent Dramas', 'independent-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Movies for ages 2 to 4', 'movies-for-ages-2-to-4' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Social Issue Dramas', 'social-issue-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Tamil-Language Movies', 'tamil-language-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Celtic Music', 'celtic-music' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Biographical Documentaries', 'biographical-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Sports Comedies', 'sports-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Extreme Sports', 'extreme-sports' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'French Dramas', 'french-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Mockumentaries', 'mockumentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Thrillers', 'classic-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Hard Rock & Heavy Metal', 'hard-rock-heavy-metal' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Adventures', 'adventures' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Crime TV Dramas', 'crime-tv-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Football Movies', 'football-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Comedies', 'classic-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Korean Movies', 'korean-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'British Movies', 'british-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Contemporary R&B', 'contemporary-rb' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Gujarati-Language Movies', 'gujarati-language-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'New Zealand Movies', 'new-zealand-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Argentinian Movies', 'argentinian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Adult Animation', 'adult-animation' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Sci-Fi Dramas', 'sci-fi-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Filipino Movies', 'filipino-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Latin Music', 'latin-music' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Shakespeare', 'shakespeare' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Variety & Talk Shows', 'tv-variety-talk-shows' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Soccer Movies', 'soccer-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Jazz', 'classic-jazz' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Gay & Lesbian Documentaries', 'gay-lesbian-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Southeast Asian Movies', 'southeast-asian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Sports Movies', 'sports-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Dark Comedies', 'dark-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Anime Sci-Fi', 'anime-sci-fi' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Punk Rock', 'punk-rock' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Period Pieces', 'period-pieces' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Cartoons', 'tv-cartoons' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'French Movies', 'french-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Country & Western/Folk', 'country-westernfolk' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Sci-Fi Adventure', 'sci-fi-adventure' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Animated Comedies', 'tv-animated-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Mindfulness & Prayer Movies', 'mindfulness-prayer-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Children & Family Movies', 'classic-children-family-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Foreign Documentaries', 'foreign-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Silent Movies', 'silent-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Martial Arts & Boxing Workouts', 'martial-arts-boxing-workouts' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Yoga', 'yoga' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Performance Art & Spoken Word', 'performance-art-spoken-word' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Courtroom Dramas', 'courtroom-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Action Sci-Fi & Fantasy', 'action-sci-fi-fantasy' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Dramas based on real life', 'dramas-based-on-real-life' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Science & Nature Documentaries', 'science-nature-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Telugu-Language Movies', 'telugu-language-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Dramedies', 'tv-dramedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'French Comedies', 'french-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Teen TV Shows', 'teen-tv-shows' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Screwball Comedies', 'screwball-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Satanic Stories', 'satanic-stories' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Dance Workouts', 'dance-workouts' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Cooking Instruction', 'cooking-instruction' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Family Sci-Fi & Fantasy', 'family-sci-fi-fantasy' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Italian Horror Movies', 'italian-horror-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Eastern European Movies', 'eastern-european-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Epics', 'epics' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Westerns', 'westerns' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Gay & Lesbian Comedies', 'gay-lesbian-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Action Thrillers', 'action-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'British TV Comedies', 'british-tv-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Foreign Sci-Fi & Fantasy', 'foreign-sci-fi-fantasy' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'French Thrillers', 'french-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV-MA', 'tv-ma' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Rock & Roll Oldies', 'rock-roll-oldies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Mysteries', 'mysteries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Abs, Glutes, & More', 'abs-glutes-more' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Stand-up Comedy', 'stand-up-comedy' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Rock & Pop', 'rock-pop' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Supernatural Thrillers', 'supernatural-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Workouts', 'workouts' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Family Dramas', 'family-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Baseball Movies', 'baseball-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Kids'' TV for ages 11 to 12', 'kids-tv-for-ages-11-to-12' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Sci-Fi & Fantasy', 'tv-sci-fi-fantasy' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Irish Movies', 'irish-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Action & Adventure', 'tv-action-adventure' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Teen Comedies', 'teen-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'African Movies', 'african-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Political Comedies', 'political-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Military Documentaries', 'military-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Tai Chi & Qigong', 'tai-chi-qigong' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Farsi-Language Movies', 'farsi-language-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Comedies', 'comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Anime Fantasy', 'anime-fantasy' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Mind and Body', 'mind-and-body' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Foreign Movies', 'classic-foreign-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Documentaries', 'documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Political Dramas', 'political-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Children & Family Movies', 'children-family-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Martial Arts, Boxing & Wrestling', 'martial-arts-boxing-wrestling' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Teen Screams', 'teen-screams' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'PG-13', 'pg-13' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Nickelodeon', 'nickelodeon' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Chinese Movies', 'chinese-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic R&B/Soul', 'classic-rbsoul' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Music & Concert Documentaries', 'music-concert-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'term', 'term' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Satires', 'satires' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Special Interest', 'special-interest' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Action & Adventure', 'classic-action-adventure' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Religious Documentaries', 'religious-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Musicals', 'musicals' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Pilates & Fitness Ball', 'pilates-fitness-ball' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Foreign Dramas', 'classic-foreign-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Movies based on children''s books', 'movies-based-on-childrens-books' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Comedies', 'tv-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Latin Pop', 'latin-pop' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Steamy Thrillers', 'steamy-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Danish Movies', 'danish-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Romantic Gay & Lesbian Movies', 'romantic-gay-lesbian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Showbiz Dramas', 'showbiz-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Foreign Comedies', 'foreign-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Boxing Movies', 'boxing-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Spy Thrillers', 'spy-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Sci-Fi Horror Movies', 'sci-fi-horror-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Style & Beauty', 'style-beauty' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Healthy Living', 'healthy-living' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'G', 'g' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Cult Comedies', 'cult-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Bollywood Movies', 'bollywood-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Dutch Movies', 'dutch-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Italian Movies', 'italian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV-Y', 'tv-y' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Urban & Dance', 'urban-dance' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'British Comedies', 'british-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Biographical Dramas', 'biographical-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV-G', 'tv-g' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Vocal Jazz', 'vocal-jazz' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Foreign Action & Adventure', 'foreign-action-adventure' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic TV Shows', 'classic-tv-shows' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic War Movies', 'classic-war-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Alien Sci-Fi', 'alien-sci-fi' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Step Aerobics Workouts', 'step-aerobics-workouts' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Gay & Lesbian Movies', 'gay-lesbian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Animal Tales', 'animal-tales' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'scheme', 'scheme' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Movies for ages 8 to 10', 'movies-for-ages-8-to-10' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Crime Action & Adventure', 'crime-action-adventure' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Sports & Fitness', 'sports-fitness' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'R', 'r' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Indian Dramas', 'indian-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Movies', 'classic-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Anime Comedies', 'anime-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV-Y7', 'tv-y7' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'British Period Pieces', 'british-period-pieces' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Crime Thrillers', 'crime-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Steamy Romantic Movies', 'steamy-romantic-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Movies for ages 5 to 7', 'movies-for-ages-5-to-7' );
INSERT INTO movie_genre ( name, url ) VALUES ( '20th Century Period Pieces', '20th-century-period-pieces' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Foreign Horror Movies', 'foreign-horror-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Military Action & Adventure', 'military-action-adventure' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Courtroom TV Dramas', 'courtroom-tv-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Monster Movies', 'monster-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Pregnancy & Parenting', 'pregnancy-parenting' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Martial Arts Movies', 'martial-arts-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Horror Movies', 'horror-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Japanese Movies', 'japanese-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Thai Movies', 'thai-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Musicals', 'classic-musicals' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Pop', 'pop' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Hobbies & Games', 'hobbies-games' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Creature Features', 'creature-features' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Singer-Songwriters', 'singer-songwriters' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Dramas', 'tv-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'World Music', 'world-music' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'British Dramas', 'british-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Arabic-Language Movies', 'arabic-language-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Political Thrillers', 'political-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Country & Western', 'classic-country-western' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Snow & Ice Sports', 'snow-ice-sports' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Rockumentaries', 'rockumentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'New Country', 'new-country' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Psychological Thrillers', 'psychological-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Social & Cultural Documentaries', 'social-cultural-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Political Documentaries', 'political-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Family Features', 'family-features' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Middle Eastern Movies', 'middle-eastern-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Asian Music', 'asian-music' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Slapstick Comedies', 'slapstick-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Family Comedies', 'family-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Vampire Movies', 'vampire-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Pregnancy & Post-Natal Fitness', 'pregnancy-post-natal-fitness' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Hungarian Movies', 'hungarian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Miniseries', 'miniseries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic TV Comedies', 'classic-tv-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Anime Series', 'anime-series' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Hindi-Language Movies', 'hindi-language-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Film Noir', 'film-noir' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Cardio & Aerobics', 'cardio-aerobics' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Car Culture', 'car-culture' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Comic Book and Superhero Movies', 'comic-book-and-superhero-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Soaps', 'tv-soaps' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'label', 'label' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Stage Musicals', 'stage-musicals' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'PG', 'pg' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV-PG', 'tv-pg' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Gangster Movies', 'gangster-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Gay & Lesbian TV Shows', 'gay-lesbian-tv-shows' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Anime Action', 'anime-action' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Comic Book & Superhero TV', 'comic-book-superhero-tv' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Sketch Comedies', 'tv-sketch-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Jazz & Easy Listening', 'jazz-easy-listening' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Romantic Movies', 'classic-romantic-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Art House Movies', 'art-house-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Teen Dramas', 'teen-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Crime TV Documentaries', 'crime-tv-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Shows', 'tv-shows' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'British Action & Adventure', 'british-action-adventure' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Russian Movies', 'russian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Music', 'music' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Foreign Gay & Lesbian Movies', 'foreign-gay-lesbian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Disney', 'disney' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Theater Arts', 'theater-arts' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Motorsports', 'motorsports' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Asian Horror', 'asian-horror' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Foreign Movies', 'foreign-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Food & Wine', 'food-wine' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Spanish Movies', 'spanish-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Czech Movies', 'czech-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV-14', 'tv-14' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Opera & Operetta', 'opera-operetta' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Gardening', 'gardening' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Bengali-Language Movies', 'bengali-language-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Sci-Fi & Fantasy', 'classic-sci-fi-fantasy' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Romantic Dramas', 'romantic-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Dramas based on a book', 'dramas-based-on-a-book' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Independent Movies', 'independent-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'British TV Dramas', 'british-tv-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Crime Documentaries', 'crime-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Tearjerkers', 'tearjerkers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Romantic Foreign Movies', 'romantic-foreign-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Kids'' TV for ages 8 to 10', 'kids-tv-for-ages-8-to-10' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Judaica', 'judaica' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Foreign Dramas', 'foreign-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Mexican Movies', 'mexican-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Documentaries', 'tv-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'B-Horror Movies', 'b-horror-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Education & Guidance', 'education-guidance' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Crime Dramas', 'crime-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Supernatural Horror Movies', 'supernatural-horror-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Jazz Greats', 'jazz-greats' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Anime Features', 'anime-features' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Wine & Beverage Appreciation', 'wine-beverage-appreciation' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Science & Technology TV Documentaries', 'science-technology-tv-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Indian Comedies', 'indian-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Dramas', 'classic-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Spy Action & Adventure', 'spy-action-adventure' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Singing Cowboy Movies', 'singing-cowboy-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Polish Movies', 'polish-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Kids'' TV for ages 0 to 2', 'kids-tv-for-ages-0-to-2' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'British Thrillers', 'british-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Modern & Alternative Rock', 'modern-alternative-rock' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Rock', 'classic-rock' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Slasher and Serial Killer Movies', 'slasher-and-serial-killer-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Independent Action & Adventure', 'independent-action-adventure' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Fantasy', 'fantasy' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Westerns', 'classic-westerns' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Mysteries', 'tv-mysteries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Low-Impact Workouts', 'low-impact-workouts' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Sports Documentaries', 'sports-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Greek Movies', 'greek-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Movies for ages 0 to 2', 'movies-for-ages-0-to-2' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Political TV Documentaries', 'political-tv-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Faith & Spirituality Movies', 'faith-spirituality-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Faith and Spirituality', 'faith-and-spirituality' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Serbo-Croatian Movies', 'serbo-croatian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Reality TV', 'reality-tv' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'NC-17', 'nc-17' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'American Folk & Bluegrass', 'american-folk-bluegrass' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Romantic Comedies', 'romantic-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Latin American Movies', 'latin-american-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Kids Music', 'kids-music' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Swedish Movies', 'swedish-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Zombie Movies', 'zombie-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Movies for ages 11 to 12', 'movies-for-ages-11-to-12' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Thrillers', 'thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Music & Concert Movies', 'music-concert-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'German Movies', 'german-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Kids'' TV', 'kids-tv' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Iranian Movies', 'iranian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Home & Garden', 'home-garden' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Nature & Ecology TV Documentaries', 'nature-ecology-tv-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Independent Comedies', 'independent-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Brazilian Movies', 'brazilian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Norwegian Movies', 'norwegian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Scandinavian Movies', 'scandinavian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Deadly Disasters', 'deadly-disasters' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Cult Sci-Fi & Fantasy', 'cult-sci-fi-fantasy' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Sci-Fi Thrillers', 'sci-fi-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Showbiz Musicals', 'showbiz-musicals' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Vocal Pop', 'vocal-pop' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Punjabi-Language Movies', 'punjabi-language-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Anime', 'anime' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Action & Adventure', 'action-adventure' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Sci-Fi & Fantasy', 'sci-fi-fantasy' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'UR', 'ur' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Family Feature Animation', 'family-feature-animation' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Werewolf Movies', 'werewolf-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Dramas based on contemporary literature', 'dramas-based-on-contemporary-literature' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Experimental Movies', 'experimental-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Theatrical Performances', 'theatrical-performances' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Belgian Movies', 'belgian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Rap & Hip-Hop', 'rap-hip-hop' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Australian Movies', 'australian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Historical Documentaries', 'historical-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'NR', 'nr' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Sports Dramas', 'sports-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'TV Westerns', 'tv-westerns' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Foreign Thrillers', 'foreign-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Independent Thrillers', 'independent-thrillers' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Home Entertaining', 'home-entertaining' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Blues', 'blues' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Dramas based on classic literature', 'dramas-based-on-classic-literature' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Afro-Cuban & Latin Jazz', 'afro-cuban-latin-jazz' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Kids'' TV for ages 2 to 4', 'kids-tv-for-ages-2-to-4' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Spiritual Documentaries', 'spiritual-documentaries' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Action Comedies', 'action-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Foreign Comedies', 'classic-foreign-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Gay & Lesbian Dramas', 'gay-lesbian-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Late Night Comedies', 'late-night-comedies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Malayalam-Language Movies', 'malayalam-language-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Israeli Movies', 'israeli-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Romantic Independent Movies', 'romantic-independent-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Military Dramas', 'military-dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Dramas', 'dramas' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Classic Horror Movies', 'classic-horror-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Anime Horror', 'anime-horror' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Sitcoms', 'sitcoms' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Family Adventures', 'family-adventures' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Kids'' TV for ages 5 to 7', 'kids-tv-for-ages-5-to-7' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Indian Movies', 'indian-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Romantic Movies', 'romantic-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'Cult Horror Movies', 'cult-horror-movies' );
INSERT INTO movie_genre ( name, url ) VALUES ( 'British TV Shows', 'british-tv-shows' );
